name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@master

      - name: Install latest stable Rust
        run: rustup update stable && rustup default stable

      - name: Compile the binary
        run: cargo build

      - name: Test the binary
        run: cargo test
